import { useState, useEffect } from 'react'
import { X, AlertCircle } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { formatFullCitation } from './SourceCitation'

/**
 * SourceForm - Citation builder form for adding/editing sources
 *
 * Props:
 * - source: existing source to edit (optional)
 * - onSave: callback with saved source
 * - onCancel: callback when cancelled
 * - isModal: whether displayed as modal (default: false)
 */

const sourceTypes = [
  { value: 'primary', label: 'Primary Source', description: 'Original record (deed book, will, patent)' },
  { value: 'derivative', label: 'Derivative', description: 'Abstract, transcription, index' },
  { value: 'authored', label: 'Authored Work', description: 'Published genealogy, analysis' },
  { value: 'research_notes', label: 'Research Notes', description: 'Working files (NOT evidence)' }
]

function SourceForm({ source = null, onSave, onCancel, isModal = false }) {
  const [formData, setFormData] = useState({
    source_type: 'derivative',
    // Primary source fields
    repository: '',
    collection: '',
    volume: '',
    page: '',
    item_description: '',
    record_date: '',
    // Published source fields
    author: '',
    title: '',
    publication_place: '',
    publisher: '',
    publication_year: '',
    page_range: '',
    // Online source fields
    url: '',
    website_name: '',
    // Common fields
    abbreviation: '',
    full_citation: '',
    original_examined: false,
    cited_in: '',
    notes: ''
  })

  const [saving, setSaving] = useState(false)
  const [error, setError] = useState(null)
  const [autoGeneratedCitation, setAutoGeneratedCitation] = useState('')

  // Load existing source data
  useEffect(() => {
    if (source) {
      setFormData({
        source_type: source.source_type || 'derivative',
        repository: source.repository || '',
        collection: source.collection || '',
        volume: source.volume || '',
        page: source.page || '',
        item_description: source.item_description || '',
        record_date: source.record_date || '',
        author: source.author || '',
        title: source.title || '',
        publication_place: source.publication_place || '',
        publisher: source.publisher || '',
        publication_year: source.publication_year || '',
        page_range: source.page_range || '',
        url: source.url || '',
        website_name: source.website_name || '',
        abbreviation: source.abbreviation || '',
        full_citation: source.full_citation || '',
        original_examined: source.original_examined || false,
        cited_in: source.cited_in || '',
        notes: source.notes || ''
      })
    }
  }, [source])

  // Auto-generate citation preview
  useEffect(() => {
    const preview = formatFullCitation(formData)
    setAutoGeneratedCitation(preview)
  }, [formData])

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setSaving(true)
    setError(null)

    try {
      // Use auto-generated citation if not manually set
      const dataToSave = {
        ...formData,
        full_citation: formData.full_citation || autoGeneratedCitation,
        publication_year: formData.publication_year ? parseInt(formData.publication_year) : null
      }

      // Remove empty string fields
      Object.keys(dataToSave).forEach(key => {
        if (dataToSave[key] === '') {
          dataToSave[key] = null
        }
      })

      let result
      if (source?.id) {
        // Update existing
        const { data, error: updateError } = await supabase
          .from('sources')
          .update(dataToSave)
          .eq('id', source.id)
          .select()
          .single()

        if (updateError) throw updateError
        result = data
      } else {
        // Insert new
        const { data, error: insertError } = await supabase
          .from('sources')
          .insert(dataToSave)
          .select()
          .single()

        if (insertError) throw insertError
        result = data
      }

      if (onSave) {
        onSave(result)
      }
    } catch (err) {
      console.error('Error saving source:', err)
      setError(err.message)
    } finally {
      setSaving(false)
    }
  }

  const formContent = (
    <form onSubmit={handleSubmit} className="space-y-6">
      {error && (
        <div className="flex items-center gap-2 p-3 bg-red-50 text-red-800 rounded-lg">
          <AlertCircle size={18} />
          <span>{error}</span>
        </div>
      )}

      {/* Source Type Selection */}
      <div>
        <label className="label">Source Type</label>
        <div className="grid grid-cols-2 gap-2">
          {sourceTypes.map(type => (
            <label
              key={type.value}
              className={`flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition-colors ${
                formData.source_type === type.value
                  ? 'border-sepia bg-sepia/5'
                  : 'border-sepia/20 hover:bg-parchment'
              }`}
            >
              <input
                type="radio"
                name="source_type"
                value={type.value}
                checked={formData.source_type === type.value}
                onChange={handleChange}
                className="mt-1"
              />
              <div>
                <span className="font-medium">{type.label}</span>
                <p className="text-xs text-faded-ink">{type.description}</p>
              </div>
            </label>
          ))}
        </div>
      </div>

      {/* Research Notes Warning */}
      {formData.source_type === 'research_notes' && (
        <div className="flex items-start gap-2 p-3 bg-yellow-50 text-yellow-800 rounded-lg">
          <AlertCircle size={18} className="mt-0.5" />
          <div>
            <p className="font-medium">Research notes are NOT evidence</p>
            <p className="text-sm">Claims from research notes need original source verification before they can support conclusions.</p>
          </div>
        </div>
      )}

      {/* Primary Source Fields */}
      {formData.source_type === 'primary' && (
        <div className="space-y-4 p-4 bg-parchment/50 rounded-lg">
          <h3 className="font-medium text-sm uppercase text-faded-ink">Primary Source Details</h3>

          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <label className="label">Repository</label>
              <input
                type="text"
                name="repository"
                value={formData.repository}
                onChange={handleChange}
                placeholder="e.g., Henrico County Courthouse"
                className="input"
              />
            </div>

            <div>
              <label className="label">Collection</label>
              <input
                type="text"
                name="collection"
                value={formData.collection}
                onChange={handleChange}
                placeholder="e.g., Deed Books"
                className="input"
              />
            </div>

            <div className="grid grid-cols-2 gap-2">
              <div>
                <label className="label">Volume</label>
                <input
                  type="text"
                  name="volume"
                  value={formData.volume}
                  onChange={handleChange}
                  placeholder="e.g., Book 3"
                  className="input"
                />
              </div>
              <div>
                <label className="label">Page</label>
                <input
                  type="text"
                  name="page"
                  value={formData.page}
                  onChange={handleChange}
                  placeholder="e.g., 45"
                  className="input"
                />
              </div>
            </div>

            <div>
              <label className="label">Record Date</label>
              <input
                type="date"
                name="record_date"
                value={formData.record_date}
                onChange={handleChange}
                className="input"
              />
            </div>

            <div>
              <label className="label">Item Description</label>
              <input
                type="text"
                name="item_description"
                value={formData.item_description}
                onChange={handleChange}
                placeholder="e.g., Michael Johnson to James Johnson, deed"
                className="input"
              />
            </div>
          </div>
        </div>
      )}

      {/* Published Source Fields */}
      {(formData.source_type === 'derivative' || formData.source_type === 'authored') && (
        <div className="space-y-4 p-4 bg-parchment/50 rounded-lg">
          <h3 className="font-medium text-sm uppercase text-faded-ink">Publication Details</h3>

          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <label className="label">Author</label>
              <input
                type="text"
                name="author"
                value={formData.author}
                onChange={handleChange}
                placeholder="e.g., Nugent, Nell Marion"
                className="input"
              />
            </div>

            <div className="col-span-2">
              <label className="label">Title</label>
              <input
                type="text"
                name="title"
                value={formData.title}
                onChange={handleChange}
                placeholder="e.g., Cavaliers and Pioneers, Vol. 1"
                className="input"
              />
            </div>

            <div>
              <label className="label">Publication Place</label>
              <input
                type="text"
                name="publication_place"
                value={formData.publication_place}
                onChange={handleChange}
                placeholder="e.g., Richmond"
                className="input"
              />
            </div>

            <div>
              <label className="label">Publisher</label>
              <input
                type="text"
                name="publisher"
                value={formData.publisher}
                onChange={handleChange}
                placeholder="e.g., Virginia State Library"
                className="input"
              />
            </div>

            <div>
              <label className="label">Publication Year</label>
              <input
                type="number"
                name="publication_year"
                value={formData.publication_year}
                onChange={handleChange}
                placeholder="e.g., 1934"
                className="input"
              />
            </div>

            <div>
              <label className="label">Page Range</label>
              <input
                type="text"
                name="page_range"
                value={formData.page_range}
                onChange={handleChange}
                placeholder="e.g., 123-125"
                className="input"
              />
            </div>
          </div>
        </div>
      )}

      {/* Research Notes Fields */}
      {formData.source_type === 'research_notes' && (
        <div className="space-y-4 p-4 bg-parchment/50 rounded-lg">
          <h3 className="font-medium text-sm uppercase text-faded-ink">Research File Details</h3>

          <div>
            <label className="label">Author/Researcher</label>
            <input
              type="text"
              name="author"
              value={formData.author}
              onChange={handleChange}
              placeholder="e.g., Johnson, Tony L."
              className="input"
            />
          </div>

          <div>
            <label className="label">Title/Description</label>
            <input
              type="text"
              name="title"
              value={formData.title}
              onChange={handleChange}
              placeholder="e.g., Tony L. Johnson Research Files"
              className="input"
            />
          </div>
        </div>
      )}

      {/* Common Fields */}
      <div className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="label">Abbreviation (Short Form)</label>
            <input
              type="text"
              name="abbreviation"
              value={formData.abbreviation}
              onChange={handleChange}
              placeholder="e.g., CPv1 or Henrico DB 3:45"
              className="input font-mono"
            />
            <p className="text-xs text-faded-ink mt-1">Used for quick reference</p>
          </div>

          <div>
            <label className="label">URL (if online)</label>
            <input
              type="url"
              name="url"
              value={formData.url}
              onChange={handleChange}
              placeholder="https://..."
              className="input"
            />
          </div>
        </div>

        {/* Original Examined Checkbox */}
        <div className="flex items-start gap-3 p-3 bg-parchment/50 rounded-lg">
          <input
            type="checkbox"
            name="original_examined"
            checked={formData.original_examined}
            onChange={handleChange}
            className="mt-1"
          />
          <div>
            <label className="font-medium cursor-pointer">Original record examined</label>
            <p className="text-xs text-faded-ink">Check if you have personally viewed the original document</p>
          </div>
        </div>

        {/* Cited In - shown if original not examined */}
        {!formData.original_examined && (
          <div>
            <label className="label">Cited In (if not examined)</label>
            <input
              type="text"
              name="cited_in"
              value={formData.cited_in}
              onChange={handleChange}
              placeholder="e.g., Cavaliers & Pioneers Vol. 3, p. 256"
              className="input"
            />
            <p className="text-xs text-faded-ink mt-1">What source did you find this citation in?</p>
          </div>
        )}

        <div>
          <label className="label">Notes</label>
          <textarea
            name="notes"
            value={formData.notes}
            onChange={handleChange}
            rows={3}
            placeholder="Any additional notes about this source..."
            className="input"
          />
        </div>
      </div>

      {/* Generated Citation Preview */}
      <div className="p-4 bg-aged-paper rounded-lg">
        <label className="label">Generated Citation</label>
        <p className="text-sm mt-1">{autoGeneratedCitation || 'Fill in fields above to generate citation'}</p>

        <div className="mt-3">
          <label className="label">Override Citation (optional)</label>
          <textarea
            name="full_citation"
            value={formData.full_citation}
            onChange={handleChange}
            rows={2}
            placeholder="Leave blank to use auto-generated citation"
            className="input text-sm"
          />
        </div>
      </div>

      {/* Actions */}
      <div className="flex justify-end gap-3">
        {onCancel && (
          <button type="button" onClick={onCancel} className="btn-secondary">
            Cancel
          </button>
        )}
        <button type="submit" disabled={saving} className="btn-primary">
          {saving ? 'Saving...' : source ? 'Update Source' : 'Add Source'}
        </button>
      </div>
    </form>
  )

  if (isModal) {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-auto">
          <div className="flex items-center justify-between p-4 border-b border-sepia/20">
            <h2 className="text-lg font-display">{source ? 'Edit Source' : 'Add New Source'}</h2>
            {onCancel && (
              <button onClick={onCancel} className="text-faded-ink hover:text-ink">
                <X size={20} />
              </button>
            )}
          </div>
          <div className="p-4">
            {formContent}
          </div>
        </div>
      </div>
    )
  }

  return formContent
}

export default SourceForm
